<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Async Await Error Handling</title>
</head>
<body>
    <h1>Async Await Error Handling</h1>

    <script>
        function makePizza(toppings = []){
            return new Promise(function( resolve, reject) {
                if (toppings.includes('pineapple')) {
                    reject('Oh no! REMOVE Pineapple');
                }
                setTimeout(() => {
                    resolve(`Your pizza is ready with ${toppings.join(', ')}`);
                }, 1000);
            });
        }

        async function go() {
            try {
                const pizza = await makePizza(['mushrooms', 'onions', 'pineapple']);
                console.log(pizza);
            } catch(err) {
                console.log(err);
            }
        }

        go();
        // makePizza(['mushrooms', 'onions']).then(results => console.log(results));
    </script>
</body>
</html>